name: Yocto Recipe Checker

on:
  pull_request:
    paths:
      - '**/*.bb'
    types: [opened, synchronize, reopened]

jobs:
  yocto-recipe-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.bb$' || true)"

    - name: Run Yocto Recipe Checker
      if: steps.changed-files.outputs.files != ''
      run: |
        ./yocto-recipe-checker.sh ${{ steps.changed-files.outputs.files }}
